//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spikes.TcpConsumer.AuthorProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddAuthorRequest", Namespace="Spike.Contracts.Authors.Requests")]
    [System.SerializableAttribute()]
    public partial class AddAuthorRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDay {
            get {
                return this.BirthDayField;
            }
            set {
                if ((this.BirthDayField.Equals(value) != true)) {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="Spike.Contracts.Authors")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDay {
            get {
                return this.BirthDayField;
            }
            set {
                if ((this.BirthDayField.Equals(value) != true)) {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Spike.Contracts.Services", ConfigurationName="AuthorProxy.IAuthorService")]
    public interface IAuthorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Contracts.Services/IAuthorService/AddAuthor", ReplyAction="Spike.Contracts.Services/IAuthorService/AddAuthorResponse")]
        Spikes.TcpConsumer.AuthorProxy.Author AddAuthor(Spikes.TcpConsumer.AuthorProxy.AddAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Contracts.Services/IAuthorService/AddAuthor", ReplyAction="Spike.Contracts.Services/IAuthorService/AddAuthorResponse")]
        System.Threading.Tasks.Task<Spikes.TcpConsumer.AuthorProxy.Author> AddAuthorAsync(Spikes.TcpConsumer.AuthorProxy.AddAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Contracts.Services/IAuthorService/GetAllAuthors", ReplyAction="Spike.Contracts.Services/IAuthorService/GetAllAuthorsResponse")]
        Spikes.TcpConsumer.AuthorProxy.Author[] GetAllAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Contracts.Services/IAuthorService/GetAllAuthors", ReplyAction="Spike.Contracts.Services/IAuthorService/GetAllAuthorsResponse")]
        System.Threading.Tasks.Task<Spikes.TcpConsumer.AuthorProxy.Author[]> GetAllAuthorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Contracts.Services/IAuthorService/GetAuthorById", ReplyAction="Spike.Contracts.Services/IAuthorService/GetAuthorByIdResponse")]
        Spikes.TcpConsumer.AuthorProxy.Author GetAuthorById(System.Guid authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Contracts.Services/IAuthorService/GetAuthorById", ReplyAction="Spike.Contracts.Services/IAuthorService/GetAuthorByIdResponse")]
        System.Threading.Tasks.Task<Spikes.TcpConsumer.AuthorProxy.Author> GetAuthorByIdAsync(System.Guid authorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorServiceChannel : Spikes.TcpConsumer.AuthorProxy.IAuthorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorServiceClient : System.ServiceModel.ClientBase<Spikes.TcpConsumer.AuthorProxy.IAuthorService>, Spikes.TcpConsumer.AuthorProxy.IAuthorService {
        
        public AuthorServiceClient() {
        }
        
        public AuthorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Spikes.TcpConsumer.AuthorProxy.Author AddAuthor(Spikes.TcpConsumer.AuthorProxy.AddAuthorRequest request) {
            return base.Channel.AddAuthor(request);
        }
        
        public System.Threading.Tasks.Task<Spikes.TcpConsumer.AuthorProxy.Author> AddAuthorAsync(Spikes.TcpConsumer.AuthorProxy.AddAuthorRequest request) {
            return base.Channel.AddAuthorAsync(request);
        }
        
        public Spikes.TcpConsumer.AuthorProxy.Author[] GetAllAuthors() {
            return base.Channel.GetAllAuthors();
        }
        
        public System.Threading.Tasks.Task<Spikes.TcpConsumer.AuthorProxy.Author[]> GetAllAuthorsAsync() {
            return base.Channel.GetAllAuthorsAsync();
        }
        
        public Spikes.TcpConsumer.AuthorProxy.Author GetAuthorById(System.Guid authorId) {
            return base.Channel.GetAuthorById(authorId);
        }
        
        public System.Threading.Tasks.Task<Spikes.TcpConsumer.AuthorProxy.Author> GetAuthorByIdAsync(System.Guid authorId) {
            return base.Channel.GetAuthorByIdAsync(authorId);
        }
    }
}
